
 CREATE  TABLE  `test`.`exif_datas` (  `filepath` varchar( 256  )  NOT  NULL ,
 `filename` varchar( 50  )  NOT  NULL ,
 `md5` varchar( 50  )  NOT  NULL ,
 `ImageWidth` int( 4  )  NOT  NULL ,
 `ImageHeight` int( 4  )  NOT  NULL ,
 `Make` text NOT  NULL ,
 `Model` text NOT  NULL ,
 `Orientation` int( 3  )  NOT  NULL ,
 `ShutterSpeed` varchar( 10  )  NOT  NULL ,
 `SutterSpeed_num` decimal( 10, 7  )  NOT  NULL ,
 `FNumber` decimal( 5, 2  )  NOT  NULL ,
 `Flash` varchar( 50  )  NOT  NULL ,
 `ExposureProgram` varchar( 50  )  NOT  NULL ,
 `ISO` int( 5  )  NOT  NULL ,
 `CreateDate` datetime NOT  NULL ,
 `ExposureCompensation` decimal( 5, 2  )  NOT  NULL ,
 `FocalLength` decimal( 5, 0  )  NOT  NULL ,
 `AFAreas` varchar( 50  )  NOT  NULL ,
 `PictureMode` varchar( 50  )  NOT  NULL ,
 `ArtFilter` varchar( 50  )  NOT  NULL ,
 `DriveMode` varchar( 50  )  NOT  NULL ,
 `FaceDetect` varchar( 50  )  NOT  NULL ,
 `FocusDistance` decimal( 6, 2  )  NOT  NULL ,
 `WhiteBalance` varchar( 50  )  NOT  NULL ,
 `LensModel` text NOT  NULL ,
 `LightValue` decimal( 5, 2  )  NOT  NULL ,
 PRIMARY  KEY (  `filepath`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = utf8;

